#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check branch
branch=$(git branch --show-current)

# Protect master and production branch from direct comit
if [[ $branch == "master" ]]; then
    echo "Direct code push to master is not allowed. Please update and merge from production."
    exit 1
elif [[ $branch == "production" ]]; then
    echo "Direct code push to production is not allowed. Please updated and merge from development."
    exit 1
elif [[ $branch == "development" ]]; then
    # Run linting and testing
    npm run lint
    npm run test
fi

exit 0
