services:
    frontend:
        image: ratndeep/chattersapp_frontend:v1.0
        container_name: frontend
        restart: always
        env_file: "client.env"
        ports:
            - 3000:3000
        networks:
            - custom-net

    backend:
        image: ratndeep/chattersapp_backend:v1.0
        container_name: backend
        env_file: "server.env"
        restart: always
        ports:
            - 8888:8888
        networks:
            - custom-net

    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        ports:
            - 6379:6379
        networks:
            - custom-net

networks:
    custom-net:
        driver: bridge
